ingress:
  beta: false
  cluster: true
  class: nginx
  adminHost: false
  serviceHost: 
  certManagerIssuerName: letsencrypt-production

pvc:
  name: 
  size: 100Mi

nakama:
  withPodInfo: true
  replicas: 3
  port: 7350
  image: heroiclabs/nakama:2.14.1
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 100Mi
      cpu: 100m

