apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-modules
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.nfsServer.pvStorage }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfsServer.clusterIP }}
    path: "/"
 