apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |-
{{- range $key, $value  := .Files.Get "custom-config.yaml" | fromYaml   }}
    {{ $key }}: 
{{- range $innerKey, $innerValue := $value   }}
      {{ $innerKey }}: {{ $innerValue }}
{{end}}
{{end}}