apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-modules
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsServer.pvcStorage }}