apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }} 
{{if .Values.ingress.cluster}}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManagerIssuerName }} 
{{else}}
    cert-manager.io/issuer: {{ .Values.ingress.certManagerIssuerName }} 
{{end}}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.serviceHost }}   
    {{ if .Values.ingress.adminHost }}   
    - {{ .Values.ingress.adminHost }}   
    {{ end }}
    secretName: {{ .Release.Name }}-tls-certificate
  rules:
    - host: {{ .Values.ingress.serviceHost }} 
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.nakama.port  }}
            path: /
            pathType: Prefix
    {{ if .Values.ingress.adminHost }}
    - host: {{ .Values.ingress.adminHost }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.nakama.port | add1 }}
            path: /
            pathType: Prefix
    {{ end }}
