apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets  }}
  {{ $k }}: {{ $v | trim}}
  {{ end }}