apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- $secrets:=  required "You need to provide a secret file with -f my-secrets.yaml, check https://otterblitzstudio.github.io/helm-charts/#/secure-distributed-nakama for more information." .Values.secrets}}
{{- range $key, $value := $secrets }}
  {{$key}}: {{$value}}
{{- end}}